name: Playwright Tests with Report Publishing

on:
  # Trigger the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allow manual triggering
  workflow_dispatch:
    inputs:
      test-tag:
        description: "Test tag to run (e.g., @sanity, @regression, @visualcomparison)"
        required: true
        default: "@regression"
      environment:
        description: "Environment to run tests against"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - preview
          - prod

jobs:
  test:
    name: Run Tests and Publish Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "tests/package-lock.json"

      - name: Install dependencies
        run: |
          cd tests
          npm ci

      - name: Install Playwright browsers
        run: |
          cd tests
          npx playwright install --with-deps chromium

      - name: Run Playwright tests
        id: run-tests
        run: |
          cd tests
          npx playwright test
        continue-on-error: true

      - name: Publish Playwright Report
        uses: your-username/playwright-report-publisher@v1
        with:
          report-directory: "tests/playwright-report"
          environment: "dev"
          report-prefix: "e2e-tests"
          post-to: "both"
          gcp-sa-key: ${{ secrets.GCP_SA_KEY }}
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          test-status: ${{ steps.run-tests.outcome == 'success' && 'passed' || 'failed' }}
